export const workflows = [
  {
    id: "capture-memory",
    name: "Preserve a family story",
    agents: ["Archivist", "Evidence reviewer", "Guardian"],
    trigger: "Member starts an interview",
    output: "Transcript, source references and a review packet",
    gate: "Storyteller consent and human review",
    steps: [
      "Keep the original in the private vault",
      "Transcribe through an approved local or cloud processor",
      "Extract candidate claims with timestamps",
      "Retain contradictions and review sharing scope",
    ],
  },
  {
    id: "scan-library",
    name: "Bring a book into the library",
    agents: ["Librarian", "OCR worker", "Evidence reviewer"],
    trigger: "An authorized scan enters quarantine",
    output: "Searchable derivative and page-linked notes",
    gate: "Rights check, malware scan and authorized collection",
    steps: [
      "Hash the original; record ownership and processing rights",
      "Inspect and scan in an isolated worker",
      "OCR each page, preserving layout and confidence",
      "Index only authorized chunks; attach page citations",
    ],
  },
  {
    id: "weekly-review",
    name: "Prepare the family review",
    agents: ["Organizer", "Librarian", "Guardian"],
    trigger: "Approved weekly schedule",
    output: "Private agenda and proposed next actions",
    gate: "Family approves decisions and outbound actions",
    steps: [
      "Read only the approved household scope",
      "Surface stale claims, missing sources and upcoming duties",
      "Prepare a short agenda without private content in logs",
      "Review together; record decisions with provenance",
    ],
  },
  {
    id: "learning-path",
    name: "Teach the next generation",
    agents: ["Learning mentor", "Librarian", "Guardian"],
    trigger: "Guardian requests a learning card",
    output: "Age-appropriate activity grounded in approved sources",
    gate: "Guardian selects audience and approves materials",
    steps: [
      "Choose a family-approved principle or source",
      "Separate family belief from historical evidence",
      "Create a practical activity with no personal profiling",
      "Guardian reviews before a child sees the material",
    ],
  },
  {
    id: "research-family",
    name: "Research with evidence",
    agents: ["Historian", "Researcher", "Evidence reviewer"],
    trigger: "Steward approves a research question",
    output: "Source-linked candidate claims and uncertainty map",
    gate: "Human accepts claims; no autonomous contact",
    steps: [
      "Search only authorized archives and public sources",
      "Record page, provenance, rights and retrieval date",
      "Preserve alternative identities and contradictory accounts",
      "Prepare candidates without merging people or publishing",
    ],
  },
  {
    id: "continuity-drill",
    name: "Practice family continuity",
    agents: ["Continuity custodian", "Preservation steward", "Guardian"],
    trigger: "Authorized recovery drill",
    output: "Restore receipt and recovery gaps",
    gate: "Trustee quorum controls recovery and release",
    steps: [
      "Select a synthetic or explicitly authorized recovery scope",
      "Verify encrypted backup fixity",
      "Restore in isolation; check links and access boundaries",
      "Record the drill; never release keys or change succession",
    ],
  },
] as const;
export const runtimeProfiles = [
  {
    id: "chatgpt",
    name: "ChatGPT Work",
    mode: "Connected workspace",
    transport: "Remote MCP with OAuth or private tunnel",
    status: "Guide available",
    purpose: "Capture, family research and approved workflow packs",
  },
  {
    id: "codex",
    name: "Codex",
    mode: "Local / cloud implementation",
    transport: "Skills + AGENTS.md + scoped MCP",
    status: "Local pack",
    purpose: "Maintain code, test policies and prepare reviewed changes",
  },
  {
    id: "lobehub",
    name: "LobeHub",
    mode: "Family-hosted chat",
    transport: "OIDC + family gateway adapter",
    status: "Adapter contract",
    purpose: "A conversational home on family-owned infrastructure",
  },
  {
    id: "open-webui",
    name: "Open WebUI",
    mode: "Family-hosted chat",
    transport: "OIDC + restricted knowledge gateway",
    status: "Adapter contract",
    purpose: "Local models and a controlled private reading room",
  },
  {
    id: "hermes",
    name: "Hermes",
    mode: "Private agent worker",
    transport: "Scoped MCP + portable skills",
    status: "Configuration example",
    purpose: "Bounded research and preparation with isolated per-member memory",
  },
  {
    id: "opencode",
    name: "OpenCode",
    mode: "Implementor workspace",
    transport: "Scoped MCP + explicit tool permissions",
    status: "Configuration example",
    purpose: "Maintain infrastructure without custodial archive access",
  },
] as const;
export const vercelDeployUrl =
  "https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Ffrankxai%2Ffamily-intelligence-os%2Ftree%2Fcodex%2Ffamily-intelligence-2026-10-02&project-name=family-intelligence-portal&repository-name=family-intelligence-portal";
